"use client"

import React, { useState } from "react"
import {
  Download,
  Printer,
  FileSpreadsheet,
  CheckCircle2,
  Calendar,
  Building2,
  Users,
  GraduationCap,
  IndianRupee,
  Layers3,
  X,
} from "lucide-react"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { useToast } from "@/hooks/use-toast"

export interface ExportReportData {
  instituteName: string
  adminName: string
  periodName: string
  dateRangeStr: string
  metrics: {
    totalStudents: number
    activeTeachers: number
    feesCollected: number
    attendanceRate: number
    totalBatches: number
  }
  students: Array<{
    id: string
    name: string
    phoneNo: string
    parentPhone?: string | null
    status: string
    joinedAt: string
    batches: string[]
    feeStatus?: string
  }>
  teachers: Array<{
    id: string
    name: string
    phoneNo: string
    specialization?: string | null
    batchCount: number
  }>
  batches: Array<{
    id: string
    className: string
    subject: string
    timing?: string | null
    teacherName?: string | null
    studentCount: number
  }>
  payments: Array<{
    id: string
    studentName: string
    batchName: string
    amount: number
    date: string
    method: string
    status: string
    receiptNo?: string
  }>
  attendanceSummary: Array<{
    date: string
    batchName: string
    total: number
    present: number
    absent: number
    rate: string
  }>
}

interface ExportReportDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  data: ExportReportData
}

export function ExportReportDialog({
  open,
  onOpenChange,
  data,
}: ExportReportDialogProps) {
  const { toast } = useToast()
  const [isExporting, setIsExporting] = useState(false)

  const generateAndDownloadCsv = () => {
    setIsExporting(true)
    try {
      const now = new Date()
      const timestamp = now.toLocaleDateString("en-IN", {
        day: "2-digit",
        month: "short",
        year: "numeric",
      })

      const lines: string[] = []

      // Helper to escape CSV strings
      const esc = (val: any) => {
        if (val === null || val === undefined) return '""'
        const str = String(val).replace(/"/g, '""')
        return `"${str}"`
      }

      // Title & Header Block
      lines.push("================================================================================")
      lines.push(`CLASSLY EDMINSTER - EXECUTIVE INSTITUTE OPERATIONS REPORT`)
      lines.push(`Institute Name: ${esc(data.instituteName)}`)
      lines.push(`Generated By: ${esc(data.adminName)}`)
      lines.push(`Report Generated On: ${esc(now.toLocaleString("en-IN"))}`)
      lines.push(`Active Reporting Period: ${esc(data.periodName)} (${esc(data.dateRangeStr)})`)
      lines.push("================================================================================")
      lines.push("")

      // Section 1: Summary
      lines.push("--------------------------------------------------------------------------------")
      lines.push("SECTION 1: SUMMARY METRICS")
      lines.push("--------------------------------------------------------------------------------")
      lines.push(["Metric", "Value", "Context"].map(esc).join(","))
      lines.push([esc("Total enrolled students"), esc(data.metrics.totalStudents), esc("Active students")].join(","))
      lines.push([esc("Teachers"), esc(data.metrics.activeTeachers), esc("Active teachers")].join(","))
      lines.push([esc("Fees collected"), esc(`₹${data.metrics.feesCollected.toLocaleString("en-IN")}`), esc(data.periodName)].join(","))
      lines.push([esc("Average attendance rate"), esc(`${data.metrics.attendanceRate}%`), esc("Recorded attendance")].join(","))
      lines.push([esc("Active batches"), esc(data.metrics.totalBatches), esc("Current batches")].join(","))
      lines.push("")

      // Section 2: Students
      lines.push("--------------------------------------------------------------------------------")
      lines.push("SECTION 2: STUDENTS")
      lines.push("--------------------------------------------------------------------------------")
      lines.push([
        "Student ID",
        "Full Name",
        "Student Phone",
        "Parent Phone",
        "Status",
        "Admission Date",
        "Enrolled Batches",
        "Tuition Status",
      ].map(esc).join(","))

      if (data.students.length === 0) {
        lines.push(["No students registered yet", "", "", "", "", "", "", ""].map(esc).join(","))
      } else {
        data.students.forEach((s) => {
          lines.push([
            esc(s.id),
            esc(s.name),
            esc(s.phoneNo),
            esc(s.parentPhone || "N/A"),
            esc(s.status),
            esc(s.joinedAt),
            esc(s.batches.join("; ") || "Unassigned"),
            esc(s.feeStatus || "ACTIVE"),
          ].join(","))
        })
      }
      lines.push("")

      // Section 3: Batches
      lines.push("--------------------------------------------------------------------------------")
      lines.push("SECTION 3: BATCHES")
      lines.push("--------------------------------------------------------------------------------")
      lines.push([
        "Batch ID",
        "Class",
        "Subject",
        "Teacher",
        "Schedule",
        "Enrolled students",
      ].map(esc).join(","))

      if (data.batches.length === 0) {
        lines.push(["No batches configured yet", "", "", "", "", ""].map(esc).join(","))
      } else {
        data.batches.forEach((b) => {
          lines.push([
            esc(b.id),
            esc(b.className),
            esc(b.subject),
            esc(b.teacherName || "Unassigned"),
            esc(b.timing || "Scheduled"),
            esc(b.studentCount),
          ].join(","))
        })
      }
      lines.push("")

      // Section 4: Fee Payments
      lines.push("--------------------------------------------------------------------------------")
      lines.push("SECTION 4: FEE PAYMENTS")
      lines.push("--------------------------------------------------------------------------------")
      lines.push([
        "Transaction ID",
        "Receipt number",
        "Student name",
        "Batch",
        "Amount (INR)",
        "Date received",
        "Payment mode",
        "Status",
      ].map(esc).join(","))

      if (data.payments.length === 0) {
        lines.push(["No transactions recorded for this period", "", "", "", "", "", "", ""].map(esc).join(","))
      } else {
        data.payments.forEach((p) => {
          lines.push([
            esc(p.id),
            esc(p.receiptNo || `REC-${p.id.slice(0, 8)}`),
            esc(p.studentName),
            esc(p.batchName),
            esc(`₹${p.amount.toLocaleString("en-IN")}`),
            esc(p.date),
            esc(p.method),
            esc(p.status),
          ].join(","))
        })
      }
      lines.push("")

      // Section 5: Attendance
      lines.push("--------------------------------------------------------------------------------")
      lines.push("SECTION 5: ATTENDANCE")
      lines.push("--------------------------------------------------------------------------------")
      lines.push([
        "Session date",
        "Batch",
        "Total enrolled",
        "Present count",
        "Absent count",
        "Attendance rate",
      ].map(esc).join(","))

      if (data.attendanceSummary.length === 0) {
        lines.push(["No attendance sessions marked in this period", "", "", "", "", ""].map(esc).join(","))
      } else {
        data.attendanceSummary.forEach((a) => {
          lines.push([
            esc(a.date),
            esc(a.batchName),
            esc(a.total),
            esc(a.present),
            esc(a.absent),
            esc(a.rate),
          ].join(","))
        })
      }
      lines.push("")
      lines.push("--- END OF REPORT ---")

      const csvContent = "data:text/csv;charset=utf-8," + encodeURIComponent(lines.join("\n"))
      const sanitizedName = data.instituteName.replace(/[^a-zA-Z0-9]/g, "_")
      const filename = `Operations_Report_${sanitizedName}_${now.toISOString().split("T")[0]}.csv`

      const link = document.createElement("a")
      link.setAttribute("href", csvContent)
      link.setAttribute("download", filename)
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)

      toast({
        title: "Report exported",
        description: "Saved as CSV.",
      })
      onOpenChange(false)
    } catch (err: any) {
      toast({
        variant: "destructive",
        title: "Export failed",
        description: err.message || "Could not generate CSV report.",
      })
    } finally {
      setIsExporting(false)
    }
  }

  const handlePrint = () => {
    window.print()
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl bg-card border-border">
        <DialogHeader>
          <div className="flex items-center gap-3">
            <div className="size-10 rounded-xl bg-primary-light text-primary flex items-center justify-center shrink-0">
              <FileSpreadsheet className="size-5" />
            </div>
            <div>
              <DialogTitle className="text-base font-bold text-foreground">
                Export report
              </DialogTitle>
              <DialogDescription className="text-xs text-muted-foreground mt-0.5">
                Export data as a spreadsheet for {data.instituteName}.
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        {/* Report Overview Card */}
        <div className="rounded-xl border border-border bg-muted/30 p-4 space-y-3 my-1">
          <div className="flex flex-wrap items-center justify-between gap-2 pb-2.5 border-b border-border text-xs">
            <div className="flex items-center gap-2">
              <Calendar className="size-3.5 text-primary" />
              <span className="font-semibold text-foreground">Period: {data.periodName}</span>
              <span className="text-muted-foreground">({data.dateRangeStr})</span>
            </div>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-1">
            <div className="p-2.5 rounded-lg bg-card border border-border">
              <p className="text-[10px] uppercase font-semibold text-muted-foreground">Students</p>
              <p className="text-base font-bold text-foreground mt-0.5">{data.metrics.totalStudents}</p>
            </div>
            <div className="p-2.5 rounded-lg bg-card border border-border">
              <p className="text-[10px] uppercase font-semibold text-muted-foreground">Teachers</p>
              <p className="text-base font-bold text-foreground mt-0.5">{data.metrics.activeTeachers}</p>
            </div>
            <div className="p-2.5 rounded-lg bg-card border border-border">
              <p className="text-[10px] uppercase font-semibold text-muted-foreground">Fees collected</p>
              <p className="text-base font-bold text-foreground mt-0.5">
                ₹{data.metrics.feesCollected.toLocaleString("en-IN")}
              </p>
            </div>
            <div className="p-2.5 rounded-lg bg-card border border-border">
              <p className="text-[10px] uppercase font-semibold text-muted-foreground">Attendance</p>
              <p className="text-base font-bold text-foreground mt-0.5">{data.metrics.attendanceRate}%</p>
            </div>
          </div>
        </div>

        {/* Section Contents Notice */}
        <div className="rounded-xl border border-border bg-card p-3.5 text-xs space-y-2">
          <p className="font-semibold text-foreground flex items-center gap-1.5">
            <CheckCircle2 className="size-3.5 text-emerald-600" />
            Report Structure Included in Spreadsheet:
          </p>
          <ul className="grid grid-cols-1 sm:grid-cols-2 gap-1.5 text-muted-foreground text-[11px] pl-5 list-disc">
            <li>Section 1: Executive KPI Overview</li>
            <li>Section 2: Student Enrollment Roster</li>
            <li>Section 3: Batches &amp; Faculty Load</li>
            <li>Section 4: Fee Ledger &amp; Collections</li>
            <li>Section 5: Attendance Compliance</li>
            <li>Formatted for Excel &amp; Google Sheets</li>
          </ul>
        </div>

        <DialogFooter className="flex flex-col sm:flex-row items-center justify-between gap-2 pt-2">
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={handlePrint}
            className="w-full sm:w-auto h-9 text-xs rounded-xl gap-1.5"
          >
            <Printer className="size-3.5" /> Print Summary
          </Button>

          <div className="flex items-center gap-2 w-full sm:w-auto">
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => onOpenChange(false)}
              className="w-full sm:w-auto h-9 text-xs rounded-xl"
            >
              Cancel
            </Button>
            <Button
              type="button"
              size="sm"
              onClick={generateAndDownloadCsv}
              disabled={isExporting}
              className="w-full sm:w-auto h-9 text-xs rounded-xl bg-primary hover:bg-primary-hover text-white gap-1.5 font-semibold cursor-pointer"
            >
              <Download className="size-3.5" />
              {isExporting ? "Generating CSV..." : "Download Spreadsheet (.CSV)"}
            </Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
